create table if not exists mcmp_cost_tst.billing_item_monthly
(
tenant_id largeint not null comment '租户id',
year                         int          not null comment '年份',
month                        int          not null comment '月份',
cloud_provider_code          varchar(20)  null comment '云提供商编码',
scope                        varchar(32)  null comment '云提供商站点',
account_id                   varchar(50)  null comment '云账户id',
resource_id                  varchar(512) null comment '资源id',
product_code                 varchar(300) null comment '产品编码',
sub_product_code             varchar(300) null comment '子产品编码',
operation                    varchar(300) null comment '各云厂商原始操作类型',
usage_type                   varchar(255) null comment '产品使用类型',
raw_sku_id                   varchar(200) null comment '原始skuid',
raw_pricing_id               varchar(200) null comment '原始pricingId',
item_type                    varchar(50)  null comment '行类型（各云厂商自定义原始类型，如Usage、DiscountedUsage）',
record_type                  varchar(50)  null comment '记录类型（将原始行类型转换后的类型，可提供给用户显示，比如DiscountedUsage会转换为Usage）',
usage_unit                   varchar(50)  null comment '单位',
purchase_option              varchar(30)  null comment '付款方式，如 All Upfront、Partial Upfront 和 No Upfront',
subscription_id              varchar(100) null comment '订阅id',
platform                     varchar(100) null comment '运行平台（操作系统）',
usage_rate_str               varchar(100) null comment '费率（分配）字符串',
raw_usage_rate_str           varchar(100) null comment '费率(原始)字符串',
resource_group               varchar(250) null comment '资源组',
cost_unit_id                 int          null comment '财务单元id',
cost_unit_full_name          varchar(200) null comment '财务单元全称',
cost_center_id               int          null comment '成本中心id',
cost_center_code             varchar(64)  null comment '成本中心编码',
cost_center_type             varchar(100) null comment '成本中心类型',
order_key                    varchar(36)  null comment '排序字段',
usage_rate decimalv3(38,18) null comment '费率(分配)',
raw_usage_rate decimalv3(38,18) null comment '费率(原始)',
resource_name                varchar(512) null comment '资源名称',
region_code                  varchar(100) null comment '区域',
available_zone               varchar(100) null comment '可用区',
account_name                 varchar(100) null comment '云账户名',
root_resource_id             varchar(200) null comment '根资源id',
root_resource_product_code   varchar(300) null comment '根资源产品编码',
root_resource_operation      varchar(300) null comment '根资源的各云厂商原始操作类型',
network                      varchar(300) null comment '网络信息',
description string null comment '资源描述',
usage_amount decimalv3(38,18) null comment '资源用量',
usage_cost decimalv3(38,18) null comment '资源消费(分配后)',
usage_begin_time             datetime     null comment '使用开始时间',
usage_end_time               datetime     null comment '使用结束时间',
reservation_usage_amount decimalv3(38,18) null comment '应用了RI部分的使用量（源明细提供的值，分账后明细中此值无意义）',
reservation_on_demand_cost decimalv3(38,18) null comment '应用了RI原始按需消费成本（非RI消费此值为0，源明细提供的值，分账后明细中此值无意义）',
reservation_effective_cost decimalv3(38,18) null comment '应用了RI的使用率的总有效成本（预留实例平摊后的有效成本，非RI消费此值为0，源明细提供的值，分账后明细中此值无意义）',
reservation_saved decimalv3(38,18) null comment '预留实例节省（=reservation_on_demand_cost-reservation_effective_cost，非RI消费此值为0，分账后明细中此值无意义）',
reservation_effective_prepay decimalv3(38,18) null comment 'RI有效预付（reservation_retrieved=fasle才有可能有值，是客户自己已经预付的钱，后期收费的时候不再追回这个费用。根据账号类型来决定，如果账号的reservation_retrieved=fasle，否则=0，分账后明细中此值无意义）',
reservation_effective_retrieve decimalv3(38,18) null comment 'RI追回费用（reservation_retrieved=tue才有可能有值)',
real_usage_cost decimalv3(38,18) null comment '实际使用费用（=usage_cost+reservation_effective_cost-reservation_effective_prepay也=raw_cost-reservation_saved-reservation_effective_prepay，分账后明细中此值无意义）',
raw_cost decimalv3(38,18) null comment '原始资源消费（如果item_type=DiscountedUsage，那么=usage_cost+reservation_on_demand_cost，否则为=usage_cost，分账前后此值均有意义）',
real_billing_applying_discount_percent decimalv3(38,18) null comment '用户实际付款所应用的折扣比例(二次定价)',
real_billing_applying_premium_percent decimalv3(38,18) null comment '用户实际付款所应用的服务费比例（二次定价）',
real_billing_applying_discount decimalv3(38,18) null comment '用户时间付款所应用的折扣金额（二次定价优惠或者增加的金额）',
real_billing_service_cost decimalv3(38,18) null comment '用户实际付款所应用的手续费金额',
real_billing_cost decimalv3(38,18) null comment '用户实际付款的钱(经过二次定价)',
raw_usage_cost decimalv3(38,18) null comment '资源消费(原始)',
currency_code                varchar(20)  null comment '币种',
currency_rate decimalv3(38,18) null comment '当月汇率',
subscription_name            varchar(200) null comment '订阅名字',
cost_unit_code               varchar(256) null comment '财务单元编码',
cost_shared                  tinyint(1)   null comment '是否费用共享（共享在统计费用时会平摊到其他，分账后明细中不应该显示cost_shared=1的记录）',
cost_independent             tinyint(1)   null comment '是否费用独立（独立核算，共享费用不会平摊到此财务单元）',
designated_shared            tinyint(1)   null comment '是否财务单元分摊（财务单元费用分摊到其他财务单元）',
cost_unit_group_id           int          null comment '财务单元组id',
cost_unit_group_code         varchar(100) null comment '财务单元组名字',
current_resource_user string null comment '当期资源使用人',
module                       varchar(200) null comment '模块',
environment                  varchar(100) null comment '环境',
instance_type                varchar(100) null comment '实例类型',
account_default_cost_unit_id int          null comment '默认项目id（当账单中无项目名称时会采用此项目）',
tags                         json         null,
create_at                    datetime     null comment '创建时间'
)
comment '资源月费用明细' engine = Doris
collate = utf-8;